# Template Sensors
# Custom sensors derived from other entities

template:
  - sensor:
      - name: "Pi-hole SID"
        state: >
          {% set tokens = states('sensor.file') | default('') | regex_findall('[^,]+') %}
          {{ tokens[0] if tokens|length > 0 else '' }}

      - name: "Pi-hole CSRF"
        state: >
          {% set tokens = states('sensor.file') | default('') | regex_findall('[^,]+') %}
          {{ tokens[1] if tokens|length > 1 else '' }}

sensor:
  - platform: history_stats
    name: "PS5 Daily Usage"
    unique_id: ps5_daily_usage
    entity_id: switch.ps5
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"
    end: "{{ now() }}"
